# Generated by Django 5.2 on 2025-08-04 15:07

import django.core.validators
import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de commande')),
                ('subtotal_fcfa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total (FCFA)')),
                ('subtotal_eur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total (EUR)')),
                ('total_fcfa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total (FCFA)')),
                ('total_eur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total (EUR)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('processing', 'En traitement'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='pending', max_length=20, verbose_name='Statut')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email client')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nom client')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone client')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='ID de paiement')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile Money'), ('wave', 'Wave')], max_length=20, verbose_name='Méthode de paiement')),
                ('amount_fcfa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (FCFA)')),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (EUR)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID de transaction')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='Réponse de la passerelle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='store.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.CharField(max_length=300, verbose_name='Description courte')),
                ('product_type', models.CharField(choices=[('formation', 'Formation'), ('livre', 'Livre'), ('ebook', 'E-book'), ('video', 'Vidéo')], default='formation', max_length=20, verbose_name='Type de produit')),
                ('price_fcfa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)')),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (EUR)')),
                ('cover_image', models.ImageField(upload_to=store.models.product_image_path, verbose_name='Image de couverture')),
                ('product_file', models.FileField(upload_to=store.models.product_file_path, verbose_name='Fichier produit')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('zip', 'ZIP'), ('mp4', 'MP4'), ('mov', 'MOV'), ('avi', 'AVI')], default='pdf', max_length=10, verbose_name='Type de fichier')),
                ('file_size', models.CharField(blank=True, max_length=20, verbose_name='Taille du fichier')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='Durée')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='Niveau')),
                ('language', models.CharField(default='Français', max_length=50, verbose_name='Langue')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('is_new', models.BooleanField(default=False, verbose_name='Nouveau')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Populaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de ventes')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Note moyenne')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'avis")),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Titre SEO')),
                ('meta_description', models.TextField(blank=True, verbose_name='Description SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('price_fcfa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)')),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (EUR)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Élément de commande',
                'verbose_name_plural': 'Éléments de commande',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='store.OrderItem', to='store.product', verbose_name='Produits'),
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_url', models.URLField(verbose_name='URL de téléchargement')),
                ('download_token', models.CharField(max_length=100, unique=True, verbose_name='Token de téléchargement')),
                ('max_downloads', models.PositiveIntegerField(default=3, verbose_name='Nombre max de téléchargements')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('last_download_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier téléchargement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='store.order', verbose_name='Commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='store.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Téléchargement',
                'verbose_name_plural': 'Téléchargements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('is_verified_purchase', models.BooleanField(default=True, verbose_name='Achat vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.order', verbose_name='Commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='Produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user', 'order')},
            },
        ),
    ]
