# Generated by Django 5.2 on 2025-08-05 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la séquence')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('video_file', models.FileField(upload_to='video_sequences/', verbose_name='Fichier vidéo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='Aperçu')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Durée (minutes)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Aperçu gratuit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sequences', to='store.product', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Séquence vidéo',
                'verbose_name_plural': 'Séquences vidéo',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
