# Generated by Django 5.2 on 2025-08-06 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_videosequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la collection')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('cover_image', models.ImageField(upload_to='collections/', verbose_name='Image de couverture')),
                ('price_fcfa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix collection (FCFA)')),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix collection (EUR)')),
                ('discount_percentage', models.PositiveIntegerField(default=0, verbose_name='Réduction (%)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Collection de livres',
                'verbose_name_plural': 'Collections de livres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalDevelopmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la section')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/', verbose_name='Image')),
                ('sub_section', models.CharField(choices=[('motivation', 'Motivation et Productivité'), ('leadership', 'Leadership et Management'), ('communication', 'Communication et Relations'), ('bien_etre', 'Bien-être et Équilibre'), ('finance', 'Finance personnelle'), ('carriere', 'Carrière et Développement professionnel')], max_length=20, verbose_name='Sous-section')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Section développement personnel',
                'verbose_name_plural': 'Sections développement personnel',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='store.bookcollection', verbose_name='Collection'),
        ),
        migrations.AddField(
            model_name='product',
            name='personal_development_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='store.personaldevelopmentsection', verbose_name='Section développement personnel'),
        ),
    ]
