# Generated by Django 5.2 on 2025-08-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_bookcollection_personaldevelopmentsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('contact_type', models.CharField(choices=[('general', 'Question générale'), ('support', 'Support technique'), ('billing', 'Facturation'), ('partnership', 'Partenariat'), ('other', 'Autre')], default='general', max_length=20, verbose_name='Type de contact')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('is_responded', models.BooleanField(default=False, verbose_name='Répondu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de téléchargements'),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_type',
            field=models.CharField(choices=[('free', 'Gratuit'), ('paid', 'Payant')], default='paid', max_length=10, verbose_name='Type de tarification'),
        ),
    ]
