# Generated by Django 5.2 on 2025-08-06 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_contact_product_downloads_count_product_pricing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='store.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.order', verbose_name='Commande'),
        ),
    ]
