# Generated by Django 5.2 on 2025-08-09 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_download_order_alter_review_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID de transaction')),
                ('operator', models.CharField(choices=[('orange', 'Orange Money'), ('mtn', 'MTN Money'), ('moov', 'Moov Money'), ('wave', 'Wave')], max_length=20, verbose_name='Opérateur')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('amount_fcfa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (FCFA)')),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (EUR)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('initiated', 'Initiated'), ('processing', 'En traitement'), ('success', 'Succès'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='pending', max_length=20, verbose_name='Statut')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID transaction passerelle')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='Réponse de la passerelle')),
                ('initiated_at', models.DateTimeField(blank=True, null=True, verbose_name='Initiated le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_transactions', to='store.order', verbose_name='Commande')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_transactions', to='store.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Transaction Mobile Money',
                'verbose_name_plural': 'Transactions Mobile Money',
                'ordering': ['-created_at'],
            },
        ),
    ]
