# Generated by Django 5.2 on 2025-08-15 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_mobilemoneytransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile Money'), ('wave', 'Wave'), ('cinetpay', 'CinetPay')], max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.CreateModel(
            name='CinetPayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID de transaction')),
                ('cinetpay_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID transaction CinetPay')),
                ('payment_token', models.CharField(blank=True, max_length=255, verbose_name='Token de paiement')),
                ('amount_fcfa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (FCFA)')),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (EUR)')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email du client')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Téléphone du client')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'En attente'), ('SUCCESS', 'Succès'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé'), ('EXPIRED', 'Expiré')], default='INITIATED', max_length=20, verbose_name='Statut')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='Réponse de la passerelle')),
                ('initiated_at', models.DateTimeField(blank=True, null=True, verbose_name='Initiated le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinetpay_transactions', to='store.order', verbose_name='Commande')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinetpay_transactions', to='store.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Transaction CinetPay',
                'verbose_name_plural': 'Transactions CinetPay',
                'ordering': ['-created_at'],
            },
        ),
    ]
