# Generated by Django 5.2 on 2025-08-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_payment_payment_method_cinetpaytransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('wave', 'Wave'), ('cinetpay', 'CinetPay')], max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.DeleteModel(
            name='MobileMoneyTransaction',
        ),
    ]
